update output action to print files that failed

diff --git a/.github/workflows/output-from-kcl-samples.yml b/.github/workflows/output-from-kcl-samples.yml
--- a/.github/workflows/output-from-kcl-samples.yml
+++ b/.github/workflows/output-from-kcl-samples.yml
@@ -28,18 +28,36 @@ jobs:
                   zoo version
                   sed -i '/---/q' README.md
                   mkdir -p {screenshots,step}
+                  failed_files=()
+
+                  # Find all .kcl files in subdirectories
                   find . -type f -name '*.kcl' | while read -r file; do
                     echo "Processing $file..."
                     fileName=$(basename "${file%.*}")
                     fileDir=$(dirname "$file")
-                    zoo kcl snapshot $file ./screenshots/$fileName.png
-                    zoo kcl export --output-format=step --src-unit=in $file ./step
-                    mv ./step/output.step ./step/$fileName.step
-                    # stabiles date (otherwise there will always be a diff)
-                    sed -E -i 's/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+[0-9]+[0-9]\+[0-9]{2}:[0-9]{2}/1970-01-01T00:00:00.0+00:00/g' ./step/$fileName.step
-                    echo "#### [$fileName]($fileDir/$fileName.kcl) ([step](step/$fileName.step)) ([screenshot](screenshots/$fileName.png))" >> README.md
-                    echo "[![$fileName](screenshots/$fileName.png)]($fileDir/$fileName.kcl)" >> README.md
+                    
+                    # Take a snapshot
+                    zoo kcl snapshot "$file" "./screenshots/$fileName.png"
+
+                    # Try to export to STEP format
+                    if zoo kcl export --output-format=step --src-unit=in "$file" "./step"; then
+                      mv "./step/output.step" "./step/$fileName.step"
+                      # Stabilize the date
+                      sed -E -i 's/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]+[0-9]+[0-9]\+[0-9]{2}:[0-9]{2}/1970-01-01T00:00:00.0+00:00/g' "./step/$fileName.step"
+                      echo "#### [$fileName]($fileDir/$fileName.kcl) ([step](step/$fileName.step)) ([screenshot](screenshots/$fileName.png))" >> README.md
+                      echo "[![$fileName](screenshots/$fileName.png)]($fileDir/$fileName.kcl)" >> README.md
+                    else
+                      echo "Failed to export $file to STEP format."
+                      failed_files+=("$file")
+                    fi
                   done
+
+                  # Report failed files
+                  if [ ${#failed_files[@]} -ne 0 ]; then
+                    echo "The following files failed to export to STEP format:"
+                    printf '%s\n' "${failed_files[@]}"
+                    exit 1
+                  fi
             - name: check for changes
               id: git-check
               run: |
